name:          "WTF, HTML and CSS?"
url:           http://wtfhtmlcss.com
repo:          https://github.com/mdo/wtf-html-css
twitter:       https://twitter.com/mdo

markdown:      redcarpet
permalink:     pretty
pygments:      true
